/**
 * Contract specification for FoldersModule (src/interfaces/folders.ts)
 *
 * This file documents the exact shape of every operation the FoldersModule
 * must satisfy. It is the canonical reference for:
 *   - tests/contracts/folders.test.ts  (RED before implementation)
 *   - src/core/modules/folders/index.ts (GREEN implementation)
 *
 * Generated by /speckit.plan on 2026-03-24.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type FolderHealthStatus = 'ok' | 'stale' | 'unknown' | 'checking';

export interface ScannedFolder {
  id: string;            // UUID
  path: string;          // absolute filesystem path (the scan root)
  displayName: string;   // basename(path)
  lastScanAt: Date;      // timestamp of last successful scan
  clipCountAtScan: number;
  filesHashAtScan: string; // 32-char lowercase hex string
  createdAt: Date;
}

export interface FolderHealthResult {
  folderId: string;
  /** Resolved health status — never 'checking' */
  status: 'ok' | 'stale' | 'unknown';
}

// ─── FoldersModule contract ───────────────────────────────────────────────────

export interface FoldersModule {
  /**
   * CONTRACT: list()
   *
   * Returns all rows from scanned_folders, ordered by lastScanAt DESC.
   * Returns an empty array when no folders have been scanned.
   *
   * Invariants:
   *   - Every returned ScannedFolder has a non-empty id and path.
   *   - displayName === path.split(/[/\\]/).at(-1)  (basename)
   *   - Returned array is sorted: list()[0].lastScanAt >= list()[1].lastScanAt
   */
  list(): ScannedFolder[];

  /**
   * CONTRACT: upsertAfterScan(dir, files)
   *
   * Creates or updates the scanned_folders record for `dir`.
   *
   * @param dir   Absolute path to the scanned directory.
   * @param files Video files discovered during the scan.
   *              Each entry: { name: string (basename), size: number (bytes) }
   *
   * Invariants:
   *   - If a record for `dir` exists, it is UPDATED (not duplicated).
   *   - The returned ScannedFolder has path === dir.
   *   - filesHashAtScan === sha256(files.map(f => `${f.name}:${f.size}`).sort().join('\n')).slice(0, 32)
   *   - clipCountAtScan === files.length
   *   - lastScanAt is set to the current time (Date.now()).
   *   - Calling twice with the same dir and same files produces the same filesHashAtScan.
   *   - Calling twice with the same dir but different files produces a different filesHashAtScan.
   */
  upsertAfterScan(dir: string, files: Array<{ name: string; size: number }>): ScannedFolder;

  /**
   * CONTRACT: healthCheck(folderId)
   *
   * Reads filesystem metadata for the folder identified by folderId and
   * returns the health status.
   *
   * @param folderId  The ScannedFolder.id to check.
   *
   * Invariants:
   *   - If folder with folderId does not exist in DB → throws FoldersModuleError('FOLDERS_NOT_FOUND')
   *   - If the folder path is NOT accessible on disk → returns { folderId, status: 'unknown' }
   *   - If the current files hash equals filesHashAtScan → returns { folderId, status: 'ok' }
   *   - If the current files hash differs from filesHashAtScan → returns { folderId, status: 'stale' }
   *   - The status is NEVER 'checking' (that is a UI-only transient state).
   *   - The check uses ONLY filename and file size (no file content reads).
   */
  healthCheck(folderId: string): Promise<FolderHealthResult>;

  /**
   * CONTRACT: remove(folderId)
   *
   * Removes the scanned_folders record and all trips/clips that belong
   * exclusively to that folder. Files on disk are NOT touched.
   *
   * @param folderId  The ScannedFolder.id to remove.
   *
   * Invariants:
   *   - If folder with folderId does not exist → throws FoldersModuleError('FOLDERS_NOT_FOUND')
   *   - After remove(), list() no longer includes the removed folder.
   *   - Trips whose first clip path starts with the removed folder's path are deleted.
   *   - Clips belonging to those trips are deleted.
   *   - Files on disk are not modified.
   *   - Operation is atomic (all-or-nothing via SQLite transaction).
   */
  remove(folderId: string): void;
}

// ─── Error type ───────────────────────────────────────────────────────────────

export type FoldersError =
  | 'FOLDERS_NOT_FOUND'    // folderId not in DB
  | 'FOLDERS_REMOVE_FAILED' // transaction failed
  | 'FOLDERS_DB_ERROR';    // unexpected DB error

// ─── IPC channel shapes ───────────────────────────────────────────────────────

/**
 * IPC channel: 'folders:list'
 * Direction: renderer → main
 * Request:  {}  (no payload)
 * Response: ScannedFolder[]
 */
export interface FoldersListResponse {
  folders: ScannedFolder[];
}

/**
 * IPC channel: 'folders:healthCheck'
 * Direction: renderer → main
 * Request:  { folderId: string }
 * Response: FolderHealthResult
 */
export interface FoldersHealthCheckRequest {
  folderId: string;
}
export type FoldersHealthCheckResponse = FolderHealthResult;

/**
 * IPC channel: 'folders:remove'
 * Direction: renderer → main
 * Request:  { folderId: string }
 * Response: { ok: true }
 */
export interface FoldersRemoveRequest {
  folderId: string;
}
export interface FoldersRemoveResponse {
  ok: true;
}

// ─── window.api shape extension ──────────────────────────────────────────────

/**
 * Preload bridge extension (added to window.api in preload/index.ts):
 *
 * window.api.folders = {
 *   list():                               Promise<ScannedFolder[]>
 *   healthCheck(folderId: string):        Promise<FolderHealthResult>
 *   remove(folderId: string):             Promise<{ ok: true }>
 * }
 */
